Set Echo on
Set Verify on


CREATE TABLE CONTACT(
    CONTACT_ID CHAR(6),
        CONSTRAINT CONTACT PRIMARY KEY (CONTACT_ID),
    TEL_NUMBER NUMBER(11) CONSTRAINT PHONE CHECK(LENGTH(TEL_NUMBER)=11),
    EMAIL VARCHAR(30) );

CREATE TABLE ADDRESS(
    ADDRESS_ID CHAR(6),
        CONSTRAINT ADDRESS_KEY PRIMARY KEY (ADDRESS_ID),
    SUBURB VARCHAR(20),
    CITY VARCHAR(20),
    POSTCODE VARCHAR(7) );

CREATE TABLE ESTATE_AGENT(
    EA_ID CHAR(3),
        CONSTRAINT AGENT_ID PRIMARY KEY(EA_ID),
    EANAME VARCHAR(24),
    HQ VARCHAR(24),
    WEBSITE VARCHAR(24) );

CREATE TABLE STAFF(
    STAFF_ID CHAR(6),
        CONSTRAINT STAFF_KEY PRIMARY KEY(STAFF_ID),
    F_NAME VARCHAR(10),
    L_NAME VARCHAR(10),
    DOB DATE,
    GENDER CHAR(1),
        CONSTRAINT GEN_STAFF CHECK (GENDER IN ('M','F','O')),
    CONTACT_ID CHAR(4) CONSTRAINT UNIQ_CONTACT UNIQUE CONSTRAINT CONTACT_FK REFERENCES CONTACT(CONTACT_ID),
    ADDRESS_ID CHAR(4) CONSTRAINT UNIQ_ADDRESS UNIQUE CONSTRAINT ADDRESS_FK REFERENCES ADDRESS(ADDRESS_ID),
    EA_ID CHAR(3) CONSTRAINT AGENT_FK REFERENCES ESTATE_AGENT(EA_ID) );

CREATE TABLE BRANCH(
    BRANCH_ID CHAR(6),
        CONSTRAINT BRANCH_KEY PRIMARY KEY(BRANCH_ID),
    BRANCH_TYPE CHAR(2) CONSTRAINT B_TYPE CHECK(BRANCH_TYPE IN ('HQ','BR')),
    EA_ID CHAR(3) CONSTRAINT AGENT_FK_BRANCH REFERENCES ESTATE_AGENT(EA_ID),
    STAFF_ID CHAR(6) CONSTRAINT STAFF_FK_BRANCH REFERENCES STAFF(STAFF_ID),
    CONTACT_ID CHAR(4) CONSTRAINT UNIQ_CONTACT_BRANCH UNIQUE CONSTRAINT CONTACT_FK_BRANCH REFERENCES CONTACT(CONTACT_ID),
    ADDRESS_ID CHAR(4) CONSTRAINT UNIQ_ADDRESS_BRANCH UNIQUE CONSTRAINT ADDRESS_FK_BRANCH REFERENCES ADDRESS(ADDRESS_ID) );

CREATE TABLE CUSTOMER(
    CUSTOMER_ID CHAR(6),
        CONSTRAINT CUST_ID PRIMARY KEY(CUSTOMER_ID),
    F_NAME VARCHAR(10),
    L_NAME VARCHAR(10),
    DOB DATE,
    GENDER Char(1)
        CONSTRAINT GEN_CUST CHECK (GENDER IN ('M','F','O')),
    CUST_TYPE CHAR(8) CONSTRAINT CHECK_CUST_TYPE CHECK(CUST_TYPE IN ('LANDLORD','TENANT','BUYER')),
    CONTACT_ID CHAR(4) CONSTRAINT UNIQ_CONTACT_CUST UNIQUE CONSTRAINT CONTACT_FK_CUST REFERENCES CONTACT(CONTACT_ID),
    ADDRESS_ID CHAR(4) CONSTRAINT UNIQ_ADDRESS_CUST UNIQUE CONSTRAINT ADDRESS_FK_CUST REFERENCES ADDRESS(ADDRESS_ID) );


CREATE TABLE PROPERTY_DESC(
    PROPDESC_ID CHAR(6),
        CONSTRAINT PROPDESC_KEY PRIMARY KEY(PROPDESC_ID),
    PROP_TYPE VARCHAR(20),
        CONSTRAINT PROP_CTGR CHECK (PROP_TYPE IN ('Purpose-built flat','Converted flat','Studio flat','Maisonette','Bungalow','Cottage','Terraced House','Semi-detached house','Detached house','Mansion house')),
    PROP_DESC VARCHAR(255),
    FURNISHED CHAR(1),
    AREA FLOAT(2),
    ACCESSIBILITY CHAR(4),
    NO_OF_ROOMS CHAR(2) );

CREATE TABLE PROPERTY(
    PROP_ID CHAR(6),
        CONSTRAINT PROPERTY_KEY PRIMARY KEY(PROP_ID),
    POSTCODE VARCHAR(7),
    HOUSENUMBER NUMBER(3),
    PROPDESC_ID CHAR(6) CONSTRAINT UNIQ_PROPDESC UNIQUE CONSTRAINT PROP_DESCKEY REFERENCES PROPERTY_DESC(PROPDESC_ID),
    REGISTERED DATE,
    ASKINGPRICE NUMBER(6) );

CREATE TABLE PROP_RENTED(
    PROP_ID CHAR(6) CONSTRAINT PROP_RFK REFERENCES PROPERTY(PROP_ID),
    TENANT_ID CHAR(6),
        CONSTRAINT TENANT_RFK FOREIGN KEY(TENANT_ID) REFERENCES CUSTOMER (CUSTOMER_ID),
    CONSTRAINT PROP_RENTED_ID PRIMARY KEY (PROP_ID, TENANT_ID),
    START_DATE DATE,
    END_DATE DATE,
    RENT_PCM NUMBER(6),
    DEPOSIT NUMBER(5),
    COMMISSION NUMBER(5) );

CREATE TABLE PROP_SOLD(
    PROP_ID CHAR(6) CONSTRAINT PROP_SFK REFERENCES PROPERTY(PROP_ID),
    BUYER_ID CHAR(6) CONSTRAINT BUYER_SFK REFERENCES CUSTOMER (CUSTOMER_ID),
    CONSTRAINT PROP_SOLD_ID PRIMARY KEY (PROP_ID, BUYER_ID),
    SELLING_PRICE NUMBER(6),
    COMMISSION NUMBER(5),
    STAMPDUTY NUMBER(5) );

CREATE TABLE REGISTERS_PROPERTY(
    PROP_ID CHAR(6) CONSTRAINT PROP_RPPC REFERENCES PROPERTY(PROP_ID),
    LANDLORD_ID CHAR(6),
        CONSTRAINT LANDLORD_RFK FOREIGN KEY(LANDLORD_ID) REFERENCES CUSTOMER (CUSTOMER_ID) );

CREATE TABLE ARRANGED_VIEWING_BY(
    PROP_ID CHAR(6) CONSTRAINT PROP_AVB REFERENCES PROPERTY(PROP_ID),
    CUSTOMER_ID CHAR(6) CONSTRAINT BUYER_AVB REFERENCES CUSTOMER (CUSTOMER_ID),
    BRANCH_ID CHAR(6)
      CONSTRAINT BRANCH_AVB REFERENCES BRANCH (BRANCH_ID),
    VIEW_DATE TIMESTAMP,
    PROP_COMMENT VARCHAR(255),
    CONSTRAINT ARRANGED_VIEWING_BY_ID PRIMARY KEY (PROP_ID, CUSTOMER_ID, BRANCH_ID)   );

CREATE TABLE TEST(
  TEST_TYPE CHAR(1) PRIMARY KEY(TEST_TYPE),
  CUST_TYPE CHAR(8) CONSTRAINT CHECK_CUST_TYPE CHECK(CUST_TYPE IN ('LANDLORD','TENANT','BUYER'))
);

DROP TABLE ESTATE_AGENT CASCADE CONSTRAINTS purge;
DROP TABLE STAFF CASCADE CONSTRAINTS purge;
DROP TABLE CONTACT CASCADE CONSTRAINTS purge;
DROP TABLE ADDRESS CASCADE CONSTRAINTS purge;
DROP TABLE BRANCH CASCADE CONSTRAINTS purge;
DROP TABLE CUSTOMER CASCADE CONSTRAINTS purge;
DROP TABLE PROPERTY CASCADE CONSTRAINTS purge;
DROP TABLE PROPERTY_DESC CASCADE CONSTRAINTS purge;
DROP TABLE PROP_RENTED CASCADE CONSTRAINTS purge;
DROP TABLE PROP_SOLD CASCADE CONSTRAINTS purge;
DROP TABLE REGISTERS_PROPERTY CASCADE CONSTRAINTS purge;
DROP TABLE ARRANGED_VIEWING_BY CASCADE CONSTRAINTS purge;
