INSERT INTO landlord_tab
SELECT CUSTOMER_ID, F_NAME, L_NAME, DOB, GENDER, Prop_reg()
FROM CUSTOMER
WHERE CUSTOMER.CUST_TYPE = 'LANDLORD';

INSERT INTO buyer_tab
SELECT CUSTOMER_ID, F_NAME, L_NAME, DOB, GENDER, Prop_bought()
FROM CUSTOMER
WHERE CUSTOMER.CUST_TYPE = 'BUYER';

INSERT INTO tenant_tab
SELECT CUSTOMER_ID, F_NAME, L_NAME, DOB, GENDER, Prop_leased()
FROM CUSTOMER
WHERE CUSTOMER.CUST_TYPE = 'TENANT';

INSERT INTO Property_tab
SELECT PROP_ID, REGISTERED, ASKINGPRICE, NULL
FROM PROPERTY;

INSERT INTO PropRented_tab
SELECT P.PROP_ID, M.REGISTERED, M.ASKINGPRICE, NULL , START_DATE, END_DATE, RENT_PCM, COMMISSION, DEPOSIT, NULL
FROM PROP_RENTED P
INNER JOIN PROPERTY M ON M.PROP_ID = P.PROP_ID;

INSERT INTO PropSold_tab
SELECT P.PROP_ID, M.REGISTERED, M.ASKINGPRICE, NULL, SOLDDATE, SELLING_PRICE, COMMISSION, STAMPDUTY, NULL
FROM PROP_SOLD P
INNER JOIN PROPERTY M ON M.PROP_ID = P.PROP_ID;


UPDATE PROPERTY_TAB
SET REG_BY = (SELECT REF(L) FROM LANDLORD_TAB L WHERE L.CUSTOMERID = '1') 
WHERE PROPID = '1' ;
UPDATE PROPERTY_TAB
SET REG_BY = (SELECT REF(L) FROM LANDLORD_TAB L WHERE L.CUSTOMERID = '2') 
WHERE PROPID = '2' ;
UPDATE PROPERTY_TAB
SET REG_BY = (SELECT REF(L) FROM LANDLORD_TAB L WHERE L.CUSTOMERID = '2') 
WHERE PROPID = '3' ;
UPDATE PROPERTY_TAB
SET REG_BY = (SELECT REF(L) FROM LANDLORD_TAB L WHERE L.CUSTOMERID = '4') 
WHERE PROPID = '4' ;
UPDATE PROPERTY_TAB
SET REG_BY = (SELECT REF(L) FROM LANDLORD_TAB L WHERE L.CUSTOMERID = '6') 
WHERE PROPID = '5' ;
UPDATE PROPERTY_TAB
SET REG_BY = (SELECT REF(L) FROM LANDLORD_TAB L WHERE L.CUSTOMERID = '1') 
WHERE PROPID = '6' ;
UPDATE PROPERTY_TAB
SET REG_BY = (SELECT REF(L) FROM LANDLORD_TAB L WHERE L.CUSTOMERID = '6') 
WHERE PROPID = '7' ;
UPDATE PROPERTY_TAB
SET REG_BY = (SELECT REF(L) FROM LANDLORD_TAB L WHERE L.CUSTOMERID = '1') 
WHERE PROPID = '8' ;
UPDATE PROPERTY_TAB
SET REG_BY = (SELECT REF(L) FROM LANDLORD_TAB L WHERE L.CUSTOMERID = '6') 
WHERE PROPID = '9' ;
UPDATE PROPERTY_TAB
SET REG_BY = (SELECT REF(L) FROM LANDLORD_TAB L WHERE L.CUSTOMERID = '1') 
WHERE PROPID = '10' ;
UPDATE PROPERTY_TAB
SET REG_BY = (SELECT REF(L) FROM LANDLORD_TAB L WHERE L.CUSTOMERID = '2') 
WHERE PROPID = '11' ;
UPDATE PROPERTY_TAB
SET REG_BY = (SELECT REF(L) FROM LANDLORD_TAB L WHERE L.CUSTOMERID = '1') 
WHERE PROPID = '12' ;
UPDATE PROPERTY_TAB
SET REG_BY = (SELECT REF(L) FROM LANDLORD_TAB L WHERE L.CUSTOMERID = '2') 
WHERE PROPID = '13' ;
UPDATE PROPERTY_TAB
SET REG_BY = (SELECT REF(L) FROM LANDLORD_TAB L WHERE L.CUSTOMERID = '2') 
WHERE PROPID = '14' ;
UPDATE PROPERTY_TAB
SET REG_BY = (SELECT REF(L) FROM LANDLORD_TAB L WHERE L.CUSTOMERID = '2') 
WHERE PROPID = '15' ;

UPDATE PropRented_tab
SET reg_by = (SELECT REF(L) FROM landlord_tab L WHERE L.CUSTOMERID = '1') 
WHERE PROPID = '1' ;
UPDATE PropRented_tab
SET reg_by = (SELECT REF(L) FROM landlord_tab L WHERE L.CUSTOMERID = '2') 
WHERE PROPID = '2' ;
UPDATE PropRented_tab
SET reg_by = (SELECT REF(L) FROM landlord_tab L WHERE L.CUSTOMERID = '4') 
WHERE PROPID = '4' ;
UPDATE PropRented_tab
SET reg_by = (SELECT REF(L) FROM landlord_tab L WHERE L.CUSTOMERID = '6') 
WHERE PROPID = '6' ;

UPDATE PropRented_tab
SET rented_by = (SELECT REF(L) FROM tenant_tab L WHERE L.CUSTOMERID = '4') 
WHERE PROPID = '1' ;
UPDATE PropRented_tab
SET rented_by = (SELECT REF(L) FROM tenant_tab L WHERE L.CUSTOMERID = '9') 
WHERE PROPID = '2' ;
UPDATE PropRented_tab
SET rented_by = (SELECT REF(L) FROM tenant_tab L WHERE L.CUSTOMERID = '8') 
WHERE PROPID = '4' ;
UPDATE PropRented_tab
SET rented_by = (SELECT REF(L) FROM tenant_tab L WHERE L.CUSTOMERID = '7') 
WHERE PROPID = '6' ;

UPDATE PropSold_tab
SET reg_by = (SELECT REF(L) FROM landlord_tab L WHERE L.CUSTOMERID = '1') 
WHERE PROPID = '8' ;
UPDATE PropSold_tab
SET reg_by = (SELECT REF(L) FROM landlord_tab L WHERE L.CUSTOMERID = '1') 
WHERE PROPID = '10' ;
UPDATE PropSold_tab
SET reg_by = (SELECT REF(L) FROM landlord_tab L WHERE L.CUSTOMERID = '2') 
WHERE PROPID = '11' ;
UPDATE PropSold_tab
SET reg_by = (SELECT REF(L) FROM landlord_tab L WHERE L.CUSTOMERID = '1') 
WHERE PROPID = '12' ;
UPDATE PropSold_tab
SET reg_by = (SELECT REF(L) FROM landlord_tab L WHERE L.CUSTOMERID = '2') 
WHERE PROPID = '13' ;
UPDATE PropSold_tab
SET reg_by = (SELECT REF(L) FROM landlord_tab L WHERE L.CUSTOMERID = '2') 
WHERE PROPID = '14' ;

UPDATE PropSold_tab
SET bought_by = (SELECT REF(L) FROM buyer_tab L WHERE L.CUSTOMERID = '3') 
WHERE PROPID = '8' ;
UPDATE PropSold_tab
SET bought_by = (SELECT REF(L) FROM buyer_tab L WHERE L.CUSTOMERID = '5') 
WHERE PROPID = '10' ;
UPDATE PropSold_tab
SET bought_by = (SELECT REF(L) FROM buyer_tab L WHERE L.CUSTOMERID = '10') 
WHERE PROPID = '11' ;
UPDATE PropSold_tab
SET bought_by = (SELECT REF(L) FROM buyer_tab L WHERE L.CUSTOMERID = '5') 
WHERE PROPID = '12' ;
UPDATE PropSold_tab
SET bought_by = (SELECT REF(L) FROM buyer_tab L WHERE L.CUSTOMERID = '10') 
WHERE PROPID = '13' ;
UPDATE PropSold_tab
SET bought_by = (SELECT REF(L) FROM buyer_tab L WHERE L.CUSTOMERID = '3') 
WHERE PROPID = '14' ;

INSERT INTO TABLE (SELECT P.REG FROM LANDLORD_TAB P WHERE P.CUSTOMERID = '1')
SELECT REF(L) FROM PROPERTY_TAB L WHERE L.REG_BY.CUSTOMERID = '1';
INSERT INTO TABLE (SELECT P.REG FROM LANDLORD_TAB P WHERE P.CUSTOMERID = '2')
SELECT REF(L) FROM PROPERTY_TAB L WHERE L.REG_BY.CUSTOMERID = '2';
INSERT INTO TABLE (SELECT P.REG FROM LANDLORD_TAB P WHERE P.CUSTOMERID = '6')
SELECT REF(L) FROM PROPERTY_TAB L WHERE L.REG_BY.CUSTOMERID = '6';

INSERT INTO TABLE (SELECT P.BOUGHT FROM BUYER_TAB P WHERE P.CUSTOMERID = '3')
SELECT REF(L) FROM PROPSOLD_TAB L WHERE L.BOUGHT_BY.CUSTOMERID = '3';
INSERT INTO TABLE (SELECT P.BOUGHT FROM BUYER_TAB P WHERE P.CUSTOMERID = '5')
SELECT REF(L) FROM PROPSOLD_TAB L WHERE L.BOUGHT_BY.CUSTOMERID = '5';
INSERT INTO TABLE (SELECT P.BOUGHT FROM BUYER_TAB P WHERE P.CUSTOMERID = '10')
SELECT REF(L) FROM PROPSOLD_TAB L WHERE L.BOUGHT_BY.CUSTOMERID = '10';


INSERT INTO TABLE (SELECT P.LEASED FROM TENANT_TAB P WHERE P.CUSTOMERID = '4')
SELECT REF(L) FROM PROPRENTED_TAB L WHERE L.RENTED_BY.CUSTOMERID = '4';
INSERT INTO TABLE (SELECT P.LEASED FROM TENANT_TAB P WHERE P.CUSTOMERID = '9')
SELECT REF(L) FROM PROPRENTED_TAB L WHERE L.RENTED_BY.CUSTOMERID = '9';
INSERT INTO TABLE (SELECT P.LEASED FROM TENANT_TAB P WHERE P.CUSTOMERID = '8')
SELECT REF(L) FROM PROPRENTED_TAB L WHERE L.RENTED_BY.CUSTOMERID = '4';
INSERT INTO TABLE (SELECT P.LEASED FROM TENANT_TAB P WHERE P.CUSTOMERID = '7')
SELECT REF(L) FROM PROPRENTED_TAB L WHERE L.RENTED_BY.CUSTOMERID = '4';


/*SELECT L.FNAME, L.LNAME, DEREF(P.REG)
FROM LANDLORD_TAB L, TABLE(L.PROPERTY_TAB) P
/*/